version: '3.8'
services:
  gateway:
    build: ./gateway
    image: gateway_image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      #      - ENV TZ=America/Mexico_City
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: server_image
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      #      - ENV TZ=America/Mexico_City
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pandora2000

  db:
    image: postgres:13.7-alpine
    container_name: shareit-db-postgres

    ports:
      - "6541:5432"
    environment:
      #      - ENV TZ=America/Mexico_City
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pandora2000